<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LambdaMOO</string>
	<key>fileTypes</key>
	<array>
		<string>moo</string>
	</array>
	<key>scopeName</key>
	<string>source.moo</string>
	<key>uuid</key>
	<string>2d1f5f3f-a8e6-44c7-9943-53f5d94772c2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.moo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.moo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.moo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.moo</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|elseif|endif|for|in|endfor|while|endwhile|try|except|endtry|return|yield)\b</string>
			<key>name</key>
			<string>keyword.control.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fork|endfork|suspend)\b</string>
			<key>name</key>
			<string>keyword.control.task.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\$(^[a-z]|\s)|@|\+|-|=|!=|&lt;|&lt;=|&gt;|&gt;=|\*|%|$|&amp;&amp;|\|\||\||\?</string>
			<key>name</key>
			<string>keyword.operator.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this|player|caller|args)\b</string>
			<key>name</key>
			<string>variable.language.builtin.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(caller_perms|set_task_perms|is_player|valid|toint|toobj|max_object|tostr|notify|has_callable_verb|verb_code|strsub|length|index|call_function|typeof|callers|parent|toliteral|task_valid|kill_task|gamevalid)\b</string>
			<key>name</key>
			<string>function.language.builtin.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.program\b</string>
			<key>name</key>
			<string>directive.language.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`|&apos;</string>
			<key>name</key>
			<string>meta.brace.try.inline.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#\d+</string>
			<key>name</key>
			<string>constant.object.number.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z]+[a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>constant.object.named.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>INT|FLOAT|STR|OBJ|LIST|ERR</string>
			<key>name</key>
			<string>constant.type.moo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>E_NONE|E_TYPE|E_DIV|E_PERM|E_PROPNF|E_VERBNF|E_INVARG|E_VARNF|E_INVIND|E_RECMOVE|E_MAXREC|E_RANGE|E_ARGS|E_NACC|E_QUOTA|E_FLOAT|ANY</string>
			<key>name</key>
			<string>constant.error.moo</string>
		</dict>
	</array>
</dict>
</plist>